<?php

/**
 * @file
 * Main hooks for Islandora DOI Block.
 */

/**
 * Implements hook_menu().
 */
function islandora_doi_block_menu() {
  return array(
    'admin/islandora/tools/doi_block' => array(
      'title' => 'Islandora DOI Block',
      'description' => 'Configure Islandora DOI Block.',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('islandora_doi_block_admin_form'),
      'access arguments' => array('administer site configuration'),
      'type' => MENU_LOCAL_TASK,
      'file' => 'includes/admin.form.inc',
    ),
  );
}

/**
 * Implements hook_block_info().
 */
function islandora_doi_block_block_info() {
  return array(
    'islandora_doi_block' => array(
      'visibility' => BLOCK_VISIBILITY_LISTED,
      'pages' => 'islandora/object/*',
      'cache' => DRUPAL_CACHE_PER_PAGE,
      'info' => t('Islandora DOI Block'),
    ),
  );
}

/**
 * Implements hook_block_view().
 */
function islandora_doi_block_block_view($delta) {
  module_load_include('inc', 'islandora_doi_block', 'includes/utilities');
  $to_render = array();
  if ($delta == 'islandora_doi_block') {
    $object = menu_get_object('islandora_object', 2);
    if ($object) {
      if (islandora_doi_block_show_for_cmodel($object)) {
        // Use new customizable list of cmodels.
        $doi = islandora_doi_block_get_doi($object);
        if ($doi) {
          // Only generate block if there is a DOI.
          $to_render['content']['doi'] = array(
            // stuff....
          );
        }
      }
    }
  }
  return $to_render;
}
